<#
.SYNOPSIS
  Builds the INTERNAL_HMAC_KEYS_JSON Script Property value from the secrets
  generated by New-Phase03C1ASecrets.ps1, and walks you through copying every
  required isolated Script Property to your clipboard one at a time — without
  ever printing a secret value to this console.

.DESCRIPTION
  Requires New-Phase03C1ASecrets.ps1 to have been run first in this same
  session (it reads $env:PHASE03C1A_HMAC_ACTIVE_SECRET,
  $env:PHASE03C1A_SESSION_TOKEN_PEPPER, $env:PHASE03C1A_CSRF_TOKEN_PEPPER).

  Only ONE HMAC key ("active") is generated for this acceptance pass — the
  runbook's retiring/disabled keys are for Phase 03B's own acceptance and are
  not required to exercise the Phase 03C1A ingress. If you want to also
  prove key-rotation behavior, add retiring/disabled entries by hand in the
  Apps Script Script Properties UI; this helper keeps the common path simple.

  For each Script Property, this script will:
    1. Copy the value to your clipboard.
    2. Print only the PROPERTY NAME (never the value) and pause.
    3. Wait for you to paste it into the isolated Apps Script Script
       Properties editor and press Enter here to continue.

  It also sets these plain (non-secret) session environment variables so the
  runner's env-loading step can read them later without you retyping them:
    $env:PHASE03C1A_KEY_ID              = "nonprod-c1a-k1"
    $env:PHASE03C1A_AUDIENCE            = "hotech-globe-tracker.apps-script.c1a-nonprod"

.NOTES
  Requires Windows PowerShell's Set-Clipboard cmdlet (built in on Windows).
#>

[CmdletBinding()]
param(
  [string]$KeyId = "nonprod-c1a-k1",
  [string]$Audience = "hotech-globe-tracker.apps-script.c1a-nonprod"
)

if (-not $env:PHASE03C1A_HMAC_ACTIVE_SECRET -or -not $env:PHASE03C1A_SESSION_TOKEN_PEPPER -or -not $env:PHASE03C1A_CSRF_TOKEN_PEPPER) {
  throw "Run .\New-Phase03C1ASecrets.ps1 first in this same PowerShell session."
}

$env:PHASE03C1A_KEY_ID = $KeyId
$env:PHASE03C1A_AUDIENCE = $Audience

# Build the key-ring JSON without ever assigning the secret to a variable
# that gets printed; construct it directly into an env var.
$keyRingJson = node -e @"
const keyId = process.env.PHASE03C1A_KEY_ID;
const secret = process.env.PHASE03C1A_HMAC_ACTIVE_SECRET;
process.stdout.write(JSON.stringify({ [keyId]: { secret, status: 'active' } }));
"@
$env:PHASE03C1A_HMAC_KEYS_JSON = $keyRingJson

function Copy-PropertyAndPause {
  param(
    [Parameter(Mandatory)][string]$PropertyName,
    [Parameter(Mandatory)][string]$Value
  )
  Set-Clipboard -Value $Value
  Write-Host ""
  Write-Host "Copied to clipboard: $PropertyName" -ForegroundColor Yellow
  Write-Host "Paste this as the Script Property named exactly '$PropertyName' in the" -ForegroundColor Yellow
  Write-Host "isolated Apps Script project's Script Properties editor." -ForegroundColor Yellow
  Read-Host "Press Enter here once pasted (this does not send anything anywhere)" | Out-Null
}

Write-Host "This will copy 4 secret/config values to your clipboard, one at a time." -ForegroundColor Cyan
Write-Host "None of them will be printed to this terminal." -ForegroundColor Cyan

Copy-PropertyAndPause -PropertyName "INTERNAL_AUDIENCE" -Value $Audience
Copy-PropertyAndPause -PropertyName "INTERNAL_HMAC_ACTIVE_KEY_ID" -Value $KeyId
Copy-PropertyAndPause -PropertyName "INTERNAL_HMAC_KEYS_JSON" -Value $env:PHASE03C1A_HMAC_KEYS_JSON
Copy-PropertyAndPause -PropertyName "SESSION_TOKEN_PEPPER" -Value $env:PHASE03C1A_SESSION_TOKEN_PEPPER
Copy-PropertyAndPause -PropertyName "CSRF_TOKEN_PEPPER" -Value $env:PHASE03C1A_CSRF_TOKEN_PEPPER

# Clear the clipboard after the last paste so the final secret does not sit
# there indefinitely.
Set-Clipboard -Value ""

Write-Host ""
Write-Host "All 4 secret/config Script Properties copied and clipboard cleared." -ForegroundColor Green
Write-Host "Still required in Script Properties (not secret, see the runbook table):" -ForegroundColor Cyan
Write-Host "  SPREADSHEET_ID                     = <your fresh isolated Sheet ID>"
Write-Host "  AUTH_SCHEMA_VERSION                = phase-03a-v1"
Write-Host "  INTERNAL_CLOCK_SKEW_SECONDS         = 30"
Write-Host "  INTERNAL_ASSERTION_MAX_TTL_SECONDS  = 60"
Write-Host "  SESSION_IDLE_TTL_SECONDS            = 1800"
Write-Host "  SESSION_ABSOLUTE_TTL_SECONDS        = 28800"
Write-Host "  SESSION_TOUCH_INTERVAL_SECONDS      = 300"
Write-Host ""
Write-Host "Next: after the Web App is deployed, run .\Set-Phase03C1ARunnerEnv.ps1" -ForegroundColor Cyan
Write-Host "to load the runner's own environment variables for the acceptance run." -ForegroundColor Cyan
